# Promise

- 자바스크립트 비동기 처리에 사용되는 객체입니다.
  - 비동기 처리 : 특정 코드의 실행이 완료될 때 까지 기다리지 않고 다음 코드를 먼저 수행하는 자바스크립트의 특성
- 보통 서버에서 받아온 데이터를 화면에 표시할 때 사용합니다.
- Promise가 코드를 동기적으로 만들 수 있게 하더라도 내부적으로는 비동기로 동작합니다.



### 1. Promise의 3가지 상태

- new Promise()로 프로미스를 생성하고 종료될 때 까지 3가지 상태를 갖습니다.
  - Pending(대기) : 비동기 처리 로직이 아직 완료되지 않은 상태
  - Fulfilled(이행) : 비동기 처리가 완료되어 프로미스가 결과 값을 반환해준 상태
  - Rejected(실패) : 비동기 처리가 실패하거나 오류가 발생한 상태

- Pending(대기)

  - 아래처럼 new Promise() 메서드를 호출하면 대기(Pending) 상태가 됩니다.
  - new Promise() 메서드를 호출할 때 콜백 함수를 선언할 수 있고, 콜백 함수의 인자는 resolve, reject입니다.

  ```javascript
  new Promise();
  
  new Promise(function(resolve, reject) {
    // ...
  });
  ```

- Fulfilled(이행)

  - 여기서 콜백 함수의 인자 resolve를 아래와 같이 실행하면 이행(Fulfilled) 상태가 됩니다.

  ```javascript
  new Promise(function(resolve, reject) {
    resolve();
  });
  ```

  - 그리고 이행 상태가 되면 아래와 같이 then()을 이용하여 처리 결과 값을 받을 수 있습니다.

  ```javascript
  function getData() {
    return new Promise(function(resolve, reject) {
      var data = 100;
      resolve(data);
    });
  }
  
  // resolve()의 결과 값 data를 resolvedData로 받음
  getData().then(function(resolvedData) {
    console.log(resolvedData); // 100
  });
  ```

- Rejected(실패)

  - 여기서 콜백 함수의 인자 reject를 아래와 같이 실행하면 실패(Rejected) 상태가 됩니다.

  ```javascript
  new Promise(function(resolve, reject) {
    reject();
  });
  ```

  - 그리고 실패 상태가 되면 실패한 이유(실패 처리의 결과 값)을 catch()로 받을 수 있습니다.

  ```javascript
  function getData() {
    return new Promise(function(resolve, reject) {
      reject(new Error("Request is failed"));
    });
  }
  
  // reject()의 결과 값 Error를 err에 받음
  getData().then().catch(function(err) {
    console.log(err); // Error: Request is failed
  });
  ```

- Promise 예제

  - 서버에서 제대로 응답을 받아오면 resolve() 메서드를 호출하고, 응답이 없으면 reject() 메서드를 호출합니다.

  ```javascript
  function getData() {
    return new Promise(function(resolve, reject) {
      $.get('url 주소/products/1', function(response) {
        if (response) {
          resolve(response);
        }
        reject(new Error("Request is failed"));
      });
    });
  }
  
  // 위 $.get() 호출 결과에 따라 'response' 또는 'Error' 출력
  getData().then(function(data) {
    console.log(data); // response 값 출력
  }).catch(function(err) {
    console.error(err); // Error 출력
  });
  ```

  

### 2. Promise Chaining

- 프로미스는 여러 개의 프로미스를 연결하여 사용할 수 있습니다.

- **then()** 메서드를 호출하고 나면 **새로운 프로미스 객체**가 반환됩니다.

  ```js
  function getData() {
    return new Promise({
      // ...
    });
  }
  
  // then() 으로 여러 개의 프로미스를 연결한 형식
  // function(data)라는 함수가 프로미스 객체를 반환해주는 함수입니다.
  getData()
    .then(function(data) {
      // ...
    })
    .then(function() {
      // ...
    })
    .then(function() {
      // ...
    });
  ```



- setTimeout() API 사용해보기

  - 프로미스 객체를 생성하고 **setTimeout()**을 이용해 2초 후 resolve()를 호출하는 예제입니다.

  ```javascript
  new Promise(function(resolve, reject){
    setTimeout(function() {
      resolve(1);
    }, 2000);
  })
  .then(function(result) {
    console.log(result); // 1
    return result + 10;
  })
  .then(function(result) {
    console.log(result); // 11
    return result + 20;
  })
  .then(function(result) {
    console.log(result); // 31
  });
  ```

  

### 3. Promise 에러 처리 방법

- 실제 서비스에서는 네트워크 연결, 서버 문제 등으로 오류가 많이 발생합니다.

- Promise는 에러처리 방법 2가지가 존재합니다.

  - 2가지 방법 모두 `reject()`메서드가 호출되어 실패 상태가 된 경우 실행됩니다.
  - `then()`의 두번째 인자로 에러를 처리하는 방법

  ```javascript
  getData().then(
    handleSuccess,
    handleError
  );
  ```

  - `catch()`를 이용하는 방법

  ```javascript
  getData().then().catch();
  ```

  

- 가급적으로는 `catch()`를 사용하는 것이 더 효율적입니다.

  - `then()`로 처리하는 경우 `then()`의 첫번째 콜백 함수 내부에서 오류가 나는 경우 오류를 제대로 잡아내지 못합니다.
  - 에러를 잡지 못했습니다(Uncaught Error)' 로그 출력

  ```javascript
  // then()의 두 번째 인자로는 감지하지 못하는 오류
  function getData() {
    return new Promise(function(resolve, reject) {
      resolve('hi');
    });
  }
  
  getData().then(function(result) {
    console.log(result);
    throw new Error("Error in then()"); // Uncaught (in promise) Error: Error in then()
  }, function(err) {
    console.log('then error : ', err);
  });
  ```

  ```javascript
  // catch()로 오류를 감지하는 코드
  function getData() {
    return new Promise(function(resolve, reject) {
      resolve('hi');
    });
  }
  
  getData().then(function(result) {
    console.log(result); // hi
    throw new Error("Error in then()");
  }).catch(function(err) {
    console.log('then error : ', err); // then error :  Error: Error in then()
  });
  ```




### 4. 다양한 예제

- 최신 ES6 문법

```javascript
const promiseTest = param => new Promise((resolve, reject) => { 
	setTimeout(() => {                 
		if (param) {
			resolve("해결 완료")
		} else {
			reject(Error("실패!!"))
		}
	}, 1000)
})

const a = promiseTest(true);
console.log(a) //node 기준 : Promise { <pending> }

setTimeout(() => {
  console.log(a); //node 기준 : Promise { '해결 완료' }
}, 1000);
```



- 분리형

```javascript
const a = new Promise((resolve, reject) => {  .
	setTimeout(() => {                  
		if (true) {
			resolve("해결 완료")
		} else {
			reject(Error("실패!!"))
		}
	}, 1000)
})

a.then(res=>{ 
    console.log(res); //1초뒤 해결완료표시, resolve 될때 까지 기다립니다.
})
```



- `.then()`, `.catch()`는 언제나 promise를 반환한다. 무한으로 이을 수 있다.

```javascript
const promiseTest = (param) =>
  new Promise((resolve, reject) => {
    setTimeout(() => {
      if (param) {
        resolve("해결 완료");
      } else {
        reject(Error("실패!!"));
      }
    }, 1000);
  });

const testRun = (param) =>
  promiseTest(param)
    .then((text) => {
      console.error(text); // 1. 해결완료 출력
      //return 1;
    })
    .catch((error) => {
      console.error(error);
    });

const a = testRun(true);

setTimeout(() => {
  console.log(a); //2. Promise { undefined } 출력 or Promise { 1 }
}, 1000);
```



- Promise 순서
  - Promise - Hi! - then
    - 실행 Queue: [ 전체 소스 실행하는  과정에서 Promise인스턴스의 함수도 같이 실행 => Fulfilled가 되면서 then 함수가 queue에 추가됨 => 계속 전체 소스 실행이 끝나고 나서 다음 번 큐에 있는 then함수가 실행 ]

```javascript
const prom = new Promise((resolve, reject) => {
  resolve()
  reject()
  console.log('Promise')
})
prom.then(() => {
  console.log('then')
})

prom.catch(() => {
  console.log('catch')
})

console.log('Hi!')
```

- Promise - Hi! - Catch

```javascript
const prom = new Promise((resolve, reject) => {
  reject()
  resolve()
  console.log('Promise')
})
prom.then(() => {
  console.log('then')
})

prom.catch(() => {
  console.log('catch')
})
```

- then이나 catch 구문은 실행 큐에 후순위로 등록되고 실행 된다.
- promise 인스턴스에 넘긴 함수 내부에서, resolve나 reject 둘 중에 먼저 호출한 것만 실제로 실행된다?
  - 사실 실제는 실행은 둘다 되지만 이미 첫번째 프로미스의 상태가 변경되면 두번째 상태는 호출할 수가 없습니다. 즉 pending상태가 아니기 때문에 실행은 되지만 무시되어 버립니다.



- 다양한 형태

  ```javascript
  new Promise((resolve, reject)=>{
      //로직
      resolve(10); 
  })
  
  Promise.resolve(10) 
  ```

  - 둘다 Promise {<resolve>: 10} 출력
  - 두개의 차이점은 첫번째 함수는 함수안에 로직을 넣어서 resolve를 진행한 것이고 두번째는 그냥 값만 resolve로 전달한 것입니다.

  ```javascript
  Promise.resolve(42)
  .then(res => { console.log(res) }) //바로 res에 42가 then으로 들어온다.
  .catch(err => { console.error(err) })
  
  Promise.reject(12)
  .then(res => { console.log(res) })
  .catch(err => { console.error(err) })//바로 err에 12가 then으로 들어온다.
  ```

  

- Promise Chaning

  - .then이나 .catch 안에서 return값이 일반값이면 promise 객체에 resolved 상태로 반환되고 그안에 값이 담깁니다. ( Promise {<resolved>: 값})
  - 하지만 .then이나 .catch 안에서 promise 인스턴스를 return 하면 **return new Promise()**와 동일

  ```javascript
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('첫번째 프라미스')
    }, 1000)
  }).then(res => {
    console.log(res) //첫번째 프라미스
    return '두번째 프라미스'
  }).then(res => {
    console.log(res) //두번째 프라미스
    return new Promise((resolve, reject) => {
      setTimeout(() => {
            resolve('세번째 프라미스')
      }, 1000)
    })
  }).then(res => { //1초뒤에 실행
    console.log(res) //세번째 프라미스
    return new Promise((resolve, reject) => {
      setTimeout(() => {
            reject('네번째 프라미스')
      }, 1000)
    })
  }).then(res => {
    console.log(res) //무시합니다.
  }).catch(err => {
    console.error(err) //1초뒤 네번째 프라미스
    return new Error('이 에러는 then에 잡힙니다.') //일반값 리턴이기 때문에 then으로 갑니다.
  }).then(res => {
    console.log(res) //바로 위의 에러메시지 출력
    throw new Error('이 에러는 catch에 잡힙니다.') //throw던짐 => 현재프로세스를 중단시키고 에러발생, 하지만 Promise는 끝까지 갑니다. 원래 보통 함수는 작업 전체를 중단되버림
  }).then(res => {
    console.log('출력 안됨') //무시
  }).catch(err => {
    console.error(err) //여기서 에러 출력
  })
  ```

  - Promise는 throw를 던져도 다른것들이 중단되지 않기 때문에 이것을 활용하기도 합니다.



- Promise.all(iterable)

  - iterable : 내부 요소들을 공개적으로 탐색(반복)할 수 있는 데이터 구조
  - Promise.all은 iterable한 객체를 인자로 받습니다.
  - **all**은 static method이기 때문에 인스턴스 new promise.all()에서는 사용할 수 없습니다.
  - 일반값은 resolved 된 값으로 간주합니다.
  - iterable 내의 모든 요소들이 resolved된 순간에 다음번 then을 호출합니다.
  - iterable 내의 일부 요소가, 하나라도 reject되면 그 순간 catch를 호출하며 reject된 값만 넘어옵니다.

  ```javascript
  const arr = [
  	1,
  	new Promise((resolve, reject) => {
  		setTimeout(()=> {
  			resolve('rejected after 1000ms')
  		}, 1000)
  	}),
  	'abc',
  	()=> 'not called function',
  	(()=> 'IIFE')()
  ]
  
  //위의 배열의 모든 것들이 resolve 될때 then을 타게 됩니다.
  //일반값은 그냥 일반값이 return, Promise 인스턴스는 resolve된 값을 return
  Promise.all(arr)
  .then(res => { console.log(res) }) //배열에 resolve된 값들이 넣어서 옵니다.
  //[ 1, 'rejected after 1000ms', 'abc', [Function], 'IIFE' ]
  .catch(err => { console.error(err) })
  ```

  ```javascript
  const arr = [
  	1,
  	new Promise((resolve, reject) => {
  		setTimeout(()=> {
  			reject('rejected after 1000ms')
  		}, 1000)
  	}),
  	'abc',
  	()=> 'not called function',
  	(()=> 'IIFE')()
  ]
  
  Promise.all(arr)
  .then(res => { console.log(res) })
  .catch(err => { console.error(err) }) //rejected after 1000ms
  ```

  

- Promise.race(iterable)

  - iterable의 요소 중 가장 먼저 fulfilled / rejected되는 요소의 결과를 then / catch에 전달.
  - 일반값은 그냥 resolved 된 값으로 간주합니다.
  - iterable 내의 요소 중에 가장 먼저 resolved (then) 또는 rejected (catch) 된 값을 반환합니다.
    - 경주한다고 생각하시면 됩니다.

  ```javascript
  const arr = [
  	new Promise(resolve => {
  		setTimeout(()=> { resolve('1번요소, 1000ms') }, 1000)
  	}),
  	new Promise(resolve => {
  		setTimeout(()=> { resolve('2번요소, 500ms') }, 500)
  	}),
  	new Promise(resolve => {
  		setTimeout(()=> { resolve('3번요소, 750ms') }, 750)
  	})
  ]
  Promise.race(arr)
  .then(res => { console.log(res) }) //2번요소, 500ms 출력
  .catch(err => { console.error(err) })
  ```

  ```javascript
  //setTimeout은 0초라도 JS는 10으로 간주, 그리고 이벤트 큐로 들어갑니다.
  const arr = [
  	new Promise(resolve => {
  		setTimeout(()=> { resolve('1번요소, 0ms') }, 0)
  	}),
  	'no queue'
  ]
  Promise.race(arr)
  .then(res => { console.log(res) }) //no queue
  .catch(err => { console.error(err) })
  ```

  

- all과 race의 비교

  - Promise.all : ALL / or / one error
  - Promise.race : only the fastest one

-  Promise로 콜백지옥(**callback hell**)을 어느정도 해결했지만 완벽히 해결하지는 못했습니다. 그래서 나온 것이 ES2017 문법 **Async Function**가 등장하게 됩니다.

  ```javascript
  function resolveAfter2Seconds() {
    return new Promise(resolve => {
      setTimeout(() => {
        resolve('resolved');
      }, 2000);
    });
  }
  
  async function asyncCall() {
    console.log('calling');
    const result = await resolveAfter2Seconds();
    console.log(result);
    // expected output: "resolved"
  }
  
  asyncCall();
  ```

  



### 5. 비동기 면접 대비

- 아래의 코드는 result가 1초 후 한꺼번에 10개가 출력됩니다. 이것을 1초 간격으로 10번 출력할 수 있을까?

```javascript
function test() {
  const promiseFunction = () =>
    new Promise((resolve) => setTimeout(() => resolve("result"), 1000));

  Array(10)
    .fill(0)
    .forEach(async () => {
      const result = await promiseFunction();
      console.log(result);
    });
}

test();
```

- 정답은 **for** 문이나 **for..of**문으로 변경하면 됩니다.

```javascript
// (1) test 앞에 async 키워드를 붙입니다.
async function test() {
    const promiseFunction = () =>
        new Promise((resolve) => setTimeout(() => resolve("result"), 1000));

    let arr = Array(10).fill(0);
  	// (2) forEach 대신 for 을 사용합니다.
    for (let i = 0; i < arr.length; i++) {
        const result = await promiseFunction();
        console.log(result);
    }
}

test();
```

```javascript
function test() {
    const promiseFunction = () =>
        new Promise((resolve) => setTimeout(() => resolve("result"), 1000));

    let array = Array(10).fill(0);
  	// (1) test를 async로 감싸는 대신, for문을 async 즉시실행함수로 감싸도 됩니다.
    (async () => {
      	// (2) forEach 대신 for ... of를 사용한다
        for (let element of array) {
            const result = await promiseFunction();
            console.log(result);
        }
    })();
}

test();
```

- 왜 forEach는 작동하지 않을까?

  - forEach의 구조

    ```javascript
    Array.prototype.forEach = function (callback) {
      for (let index = 0; index < this.length; index++) {
        callback(this[index], index, this);
      }
    };
    ```

    - forEach는 배열 요소를 돌면서 callback을 실행할 뿐, 한 callback이 끝날때 까지 기다렸다가 다음 callback을 실행하는 것이 아닙니다.
    - 즉 forEach는 자신이 실행하는 callback 함수가 비동기 작업을 하는지 안하는지 아무런 관심이 없습니다.

  - 그렇다면 forEach가 callback의 비동기 작업이 끝날때 까지 기다릴 수 있도록 하는 방법이 있을까?

    - forEach 자체를 async 함수로 만들고, 각 callback 을 await 하게 만들면 가능합니다.

    ```javascript
    async function asyncForEach(array, callback) {
      for (let index = 0; index < array.length; index++) {
        const result = await callback(array[index], index, array);
        console.log(result)
      }
    }
    ```

    

- 배열 요소들에 대한 비동기 작업

  - 순차처리 : 배열의 요소들에 대해 차례대로 비동기 작업을 수행하는 것으로, 실행 순서가 보장되어야 할 때 사용합니다.
  - 병렬 처리 : 배열의 요소들에 대해 한꺼번에 여러 비동기 작업을 수행하는 것으로, 실행 순서가 중요하지 않을 때 사용합니다. 앞서 **forEach**를 **for** 또는 **for ... of** 로 바꿔줌으로써 순차처리를 구현했습니다. 하지만 성능이 중요한 실무에서는, 순서가 중요하지 않다면 일반적으로 병렬처리를 해주는 것이 더 효율적일 것입니다.

- 비동기 작업 병렬처리 구현하기

  - Promise.all을 활용합니다.
  - 예시 : 약 1초만에 3가지 작업이 완료됩니다.

  ```javascript
  const target_url = ["ur11", "ur12", "url3"];
  
  // 다운로드에 약 1초가 걸리는 비동기 함수라고 가정
  function async_download(url) {
      return new Promise((resolve, reject) => {
          setTimeout(() => {
              console.log(url);
              resolve();
          }, 1000);
      });
  }
  
  async function parallel(array) {
      const promises = array.map((url) => async_download(url));
      await Promise.all(promises);
      console.log("all done");
  }
  
  parallel(target_url);
  //ur11
  //ur12
  //url3
  //all done
  ```

- `Promise.all`과 `forEach`와 다른점은 무엇인가요?

  - `Promsie.all`과 달리 all done이 먼저 찍힙니다.
  - `forEach`는 배열을 돌며 callback을 호출하기만 하면 맡은 바 임무를 다 한 것으로 생각하고 종료됩니다.
  - 즉 callback함수들이 `pending` 상태로 `resolve` 되지 않았지만 forEach 입장에서는 할 일을 다했으니 그대로 진행한 것입니다.
  - forEach는 콜백만 실행하고 끝나버리기에 비동기 작업의 처리 상태를 추적하지 못하고, 따라서 이후의 흐름을 제어하기도 어렵습니다.
  - 그래서 map과 `promise.all`을 사용하면 callback들이 return하는 promise 들을 새로운 배열에 잘 담아두었다가 모든 promise가 resolved 되는 타이밍을 감지할 수 있기 때문에 배열의 요소들에 비동기 작업을 실시한 후 (순차든, 병렬이든), 어떤 작업을 해야 한다면 forEach가 아닌 `map`과 `Promise.all`을 사용하는 것이 좋습니다.

  ```javascript
  const target_url = ["ur11", "ur12", "url3"];
  
  function async_download(url) {
      return new Promise((resolve, reject) => {
          setTimeout(() => {
              console.log(url);
              resolve();
          }, 1000);
      });
  }
  
  async function parallel(array) {
      array.forEach(async (url) => {
          await async_download(url);
      });
    	// all done은 언제 찍힐까?
      await console.log("all done");
  }
  
  parallel(target_url);
  //all done
  //ur11
  //ur12
  //url3
  ```

  

